language: go
sudo: false
matrix:
  include:
  - os: linux
    go: 1.10.x
    env:
    - TARGET=linux
    - ARCH=amd64
before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
notifications:
  email: false
script:
- make release && make test
deploy:
  - provider: s3
    access_key_id: AKIAIXXEON53QC2UQBPA
    secret_access_key:
      secure: NzyHE+EJQ7H2n11M6z6C5Xw7hX0MWXQmTTtmYepSTMTqwEhd5dk4MtAU5ot4RWqk7paR3J4XLVpyYPAuc8h7KCCIgzTEF0OS65z108FIurc4amGcrcbNMzQd/YEsnI71C2mm4nwsYmooFbXWRo2/yRy5015m1rS+RLfh4Pz6GSanGGtkbl1Vv2UTcyLMqCF+cMsqfChUiXe6v+x3uzFhIbfCgZVj+Ot1SSMgHSdXgiyF0XdEnpgIloDCbHUd0uTt2cuLoMDqE58jnHcLfKINfl7Jr8NS0IH0VjIR8AGy3fS9/NtbFRc27z+Esk+rDMFwTOym2QoshMWulalEcmc0un2r7XwP/rmDp+ytKSjqq1cetVD9rxBlFcHUd7YXkFyXK4Rz5pmVhzeNaXlbMOnm6BCuC2tF3Rzf4X8VcNBPqvA9NbOh6o6QraXuI2qqhNPIRSB0azvt2YLH2R4GMdC1Nytzr2w82mhNaQsvX7F+asZr4fDo+FxOnaO9nIMmmLHOzjBEGtC6km1dUmzuHUvOvlGItvyI9jbU4cqxNp3fyQc5v1uTmQavDyhcsMAkCpLdf1EUpRCmgyD43cIdkJIjlG2uFxa5jKR7eXU845t5uie7ed33n+ATVrBuAzHvM12TPxYc70JF1mjEEI8XNQIcsSMvZMiPQ0bcp84+RtuEvdU=
    bucket: telia-oss
    region: eu-west-1
    local-dir: build
    upload-dir: concourse-sts-lambda
    acl: public_read
    skip_cleanup: true
    on:
      repo: telia-oss/concourse-sts-lambda
      tags: true
  - provider: releases
    api_key:
      secure: nirsFIP2+/ZtJQ0JI5xBc0FBDfvdOZi6/qjsjjA07GluxSQPwL/2ZDOu5UYb3KXZimukOwYvoihnbMStywIw4IAmeUGjHejSQP/iu0FJNU3vp0/ud04e7Vq78/2doYvM0t0oSwL5vrr1NjrlAmQfICgyOik7ZikdjoaX5mSw/WYuc4ByKNFqjlg4rxSF5zYtUSxc/KylvrWt7E0DzsWQHo1FHH/JB8itZHcp4L++RwLffpN2ybHMbuTbHOuNh3Um/H3NmjjCnUwXRo72qDCkQHcMZ14BEoLJi/6KvAexP+6XMXx41B9NUCcUG0Sv7HmWV2RQ+JINtQtLNWbIYNZCDlU4vRkOyGL2xJjm/iCsZz/XqlH2c8ewWZMSP5jg2ZRQhm5aech2TvodCJIwxhy5stds4GjpensAlSYO/HFso9UtgYf0MIP89eFFm4Mghsz0WpkEusn1VGPHdNXZM1l7e3KqjXobuns9mpfjIg61AXsYlPf90TzHX7Vu1Fs0aR5A47RcWTYW5ChgnqJlH31j042+FyQQzN/MBg/i2xCXExg1Cu1WNLz3L23Sle9BCTuYtDM8xd0rXRItHFO/CpNcTWY9mAEarGu90Fif98sCYxU+LLaWVGBYxZuBdpNXXIsHSBM6QHHXoz7HE+YpmQZ17/Je1g51jRHT/jAOE/f+h+E=
    file: build/concourse-sts-lambda.zip
    skip_cleanup: true
    on:
      repo: telia-oss/concourse-sts-lambda
      tags: true
