language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

notifications:
  email: false

install:
  - curl -sL https://taskfile.dev/install.sh | sh
  - curl -sL https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip -o terraform.zip
  - sudo unzip terraform.zip -d /usr/bin && rm -f terraform.zip
  - go install github.com/golang/mock/mockgen

script:
  - ./bin/task test build

deploy:
  - provider: releases
    api_key:
      secure: Tg0kKbNvvwuuIJ5XFgXWQNjF2j0zZfaq+oHQelW8zK+Zv3gQJdGwKWPSY+uwmhW8zLTK/BBCx6hrwcs3AHEvYOx/Knp7mpUgwjyeyzZ1FHsz/5qzM+KaZb5guq6M6Oy9POA2DJNb87TVzPd5lkQLXqsvTlzrHhAWHLTmWkJFYOTyKodZ47VEZAu7wUlPZ3dTsiWePKG7Mm//rArK9tylhy1Fj0VKG0wZq+apEtdWImXPKpKe/66In8XsAUnijCivILybD5/hKOj8ytdoRjxGbfhirE36L8Ad+H9Wv6yTjkuUchTFVyDaXZTiT0GGHBXXwrBhwHgZo7CNGSRCFnOS1JEs9/msB5O8ckZVAJne3vBIDbBYEup8nybmgq/deegMB+NpQZrhvpOVVXHWwrflIk6+UkOWHv3l1B1EkZ5c+IxBvOBJSsMd55Ps0ARvYyXt/fN8orNH5nCBcG1o5eBKXttril55VRRgAfwMbP7ZVgBsfiEXV5XiQJEBftfkGbz1wKSj3yTS1Ep3vBCo00ngVC+BVoE2uXwqPnbcB8rzBBLKJ/QStrz++nnLSTX/kKCCdBKDIjonijXNbR8oD3TJtxSU34uQK2rw5KPt/i3rfOA2eHPT8gLYMmg0wWiV2GL/VHGX4rMCyZh9yk4BQ2KN3S2E5AxxtLxHU1Ttl/yoq1E=
    file: build/concourse-sts-lambda.zip
    skip_cleanup: true
    on:
      repo: telia-oss/concourse-sts-lambda
      tags: true

  - provider: s3
    access_key_id: AKIAIXXEON53QC2UQBPA
    secret_access_key:
      secure: NzyHE+EJQ7H2n11M6z6C5Xw7hX0MWXQmTTtmYepSTMTqwEhd5dk4MtAU5ot4RWqk7paR3J4XLVpyYPAuc8h7KCCIgzTEF0OS65z108FIurc4amGcrcbNMzQd/YEsnI71C2mm4nwsYmooFbXWRo2/yRy5015m1rS+RLfh4Pz6GSanGGtkbl1Vv2UTcyLMqCF+cMsqfChUiXe6v+x3uzFhIbfCgZVj+Ot1SSMgHSdXgiyF0XdEnpgIloDCbHUd0uTt2cuLoMDqE58jnHcLfKINfl7Jr8NS0IH0VjIR8AGy3fS9/NtbFRc27z+Esk+rDMFwTOym2QoshMWulalEcmc0un2r7XwP/rmDp+ytKSjqq1cetVD9rxBlFcHUd7YXkFyXK4Rz5pmVhzeNaXlbMOnm6BCuC2tF3Rzf4X8VcNBPqvA9NbOh6o6QraXuI2qqhNPIRSB0azvt2YLH2R4GMdC1Nytzr2w82mhNaQsvX7F+asZr4fDo+FxOnaO9nIMmmLHOzjBEGtC6km1dUmzuHUvOvlGItvyI9jbU4cqxNp3fyQc5v1uTmQavDyhcsMAkCpLdf1EUpRCmgyD43cIdkJIjlG2uFxa5jKR7eXU845t5uie7ed33n+ATVrBuAzHvM12TPxYc70JF1mjEEI8XNQIcsSMvZMiPQ0bcp84+RtuEvdU=
    bucket: telia-oss
    region: eu-west-1
    local-dir: build
    upload-dir: concourse-sts-lambda
    acl: public_read
    skip_cleanup: true
    on:
      repo: telia-oss/concourse-sts-lambda
      tags: true
